version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wish_wall_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Wish_wall@2025
      MYSQL_DATABASE: wish_wall
      MYSQL_USER: wish_wall_user
      MYSQL_PASSWORD: Wish_wall@2025
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - wish_wall_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  db_test:
    image: mysql:8.0
    container_name: wish_wall_db_test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Wish_wall@2025
      MYSQL_DATABASE: wish_wall_test
      MYSQL_USER: wish_wall_test_user
      MYSQL_PASSWORD: Wish_wall@2025
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    networks:
      - wish_wall_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wish_wall_app
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Wish_wall@2025
      - DB_NAME=wish_wall
      - DB_CHARSET=utf8mb4
      - SECRET_KEY=10ed11c41c9fd9fe27cdc7627559190f3069269ab79bc663fee6a6d3d1e543c4
      - JWT_SECRET_KEY=302ccde97f7c4f5eb87ad5966025017159b4a578dad6a9e4c0fca70a42851758
      - FLASK_ENV=development
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wish_wall_network

volumes:
  mysql_data:
  mysql_test_data:

networks:
  wish_wall_network:
    driver: bridge 